name: getstream_flutter_example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.3
  crypto: ^3.0.6
  dart_jsonwebtoken: ^2.14.1
  dartz: ^0.10.1
  #  device_info_plus: ^11.1.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
#  flutter_callkit_incoming: ^2.0.4+2

  firebase_app_check: ^0.3.1+3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_database: ^11.1.4
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.2
  get_it: ^8.0.0
  http: ^1.2.2
  permission_handler: ^11.3.1
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  stream_chat_flutter: ^8.1.0
  stream_video_flutter: ^0.6.0
  stream_video_push_notification: ^0.6.0
  stream_video_screen_sharing: ^0.6.0
  uuid: ^4.5.1
  flutter_svg: ^2.0.16
#  uni_links: ^0.5.1

dependency_overrides:
  flutter_callkit_incoming:
    path: packages/flutter_callkit_incoming-master


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  build_test: ^2.2.2
  build_web_compilers: ^4.0.11
  envied_generator: ^0.5.4+1
  go_router_builder: ^2.3.1
  import_sorter: ^4.6.0
  pubspec_dependency_sorter: ^1.0.4

  flutter_lints: ^4.0.0

import_sorter:
  emojis: true

flutter:
  uses-material-design: true

  assets:
    - assets/