// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvSlXp5XBWfp4vy6DxAp4ArX1GKxzkkD4',
    appId: '1:871056472442:web:a085ff29e3d3a5228a3ec3',
    messagingSenderId: '871056472442',
    projectId: 'getstream-flutter-example',
    authDomain: 'getstream-flutter-example.firebaseapp.com',
    storageBucket: 'getstream-flutter-example.appspot.com',
    measurementId: 'G-L178ST726N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsrxppoha6wcIBX06vgl5_ovxUYlHJHFc',
    appId: '1:871056472442:android:24f6f8c6eca8b64e8a3ec3',
    messagingSenderId: '871056472442',
    projectId: 'getstream-flutter-example',
    storageBucket: 'getstream-flutter-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCXOdWgWRHuBJt7ewiYOP80wAeUDpMRGc',
    appId: '1:871056472442:ios:9eb9da368bb5153b8a3ec3',
    messagingSenderId: '871056472442',
    projectId: 'getstream-flutter-example',
    storageBucket: 'getstream-flutter-example.appspot.com',
    iosBundleId: 'com.klilmhdi.getstreamflutterexample.getstreamFlutterExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvSlXp5XBWfp4vy6DxAp4ArX1GKxzkkD4',
    appId: '1:871056472442:web:346b975cdf2e25c38a3ec3',
    messagingSenderId: '871056472442',
    projectId: 'getstream-flutter-example',
    authDomain: 'getstream-flutter-example.firebaseapp.com',
    storageBucket: 'getstream-flutter-example.appspot.com',
    measurementId: 'G-DWK9WCR5R5',
  );
}
